name       : haskell-these
version    : 1.1
release    : 1
source     :
    - https://hackage.haskell.org/package/these-1.1/these-1.1.tar.gz : bb0beb19e4f2722e09d02413f657c456c490ea9b256b6c9f167645a8b84cb137
license    : BSD-3-Clause
component  : programming.haskell
summary    : An either-or-both data type.
description: |
    An either-or-both data type.
builddeps  :
    - haskell-base-compat-devel
    - haskell-cabal-install
    - haskell-hashable-devel
rundeps    :
    - devel:
        - haskell-base-compat-devel
        - haskell-hashable-devel
networking : yes
setup      : |
    %cabal_configure -f -assoc
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
